# Generated by Django 5.0.7 on 2024-07-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hiragana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unicode', models.CharField(max_length=8)),
                ('pronounce', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unicode', models.CharField(max_length=8)),
                ('pronounce', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Katakana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unicode', models.CharField(max_length=8)),
                ('pronounce', models.CharField(max_length=6)),
            ],
        ),
    ]
