# Generated by Django 5.0.7 on 2024-07-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japanese', '0003_alter_hiragana_unicode_alter_kanji_unicode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiragana',
            name='kanaletter',
            field=models.CharField(default='NA', max_length=8),
        ),
        migrations.AddField(
            model_name='katakana',
            name='kanaletter',
            field=models.CharField(default='NA', max_length=8),
        ),
    ]
